export { Design } from './Design.schema'
export { Seo } from './Seo.schema'
export { Media } from './Media.schema'
export { Padding } from './Padding.schema'
export { Color } from './Color.schema'
export { SectionSettings } from './SectionSettings.schema'
