export { CallToAction2 } from './old/CallToAction2.schema'
export { LogoGallery2 } from './old/LogoGallery2Type.schema'
export { ArticlesType } from './old/ArticlesType.schema'
export { textWithIllustration } from './old/textWithIllustration.schema'
export { textContainerType } from './old/textContainerType.schema'
export { EmployeesType } from './old/EmployeesType.schema'
export { contactFormType } from './old/contactForm.schema'
export { Hero2Type } from './old/Hero2Type.schema'
export { Hero3Type } from './old/Hero3Type.schema'
export { formType } from './old/formType.schema'
export { videoType } from './old/videoType.schema'
export { EventType } from './old/EventsType.schema'
export { MediaType } from './old/MediaType.schema'
export { innerBlocks } from './old/innerBlocks.schema'
export { pageBuilder } from './pageBuilder.schema'

//------//
export { DataType } from './dataType.schema'
export { GalleryType } from './GalleryType.schema'
export { pageTitle } from './pageTitle.schema'
export { ProcessType } from './ProcessType.schema'
export { Downloadables } from './downloadables.schema'
export { difSlider } from './difSlider.schema'
export { NewsLetterCTA } from './NewsLetterCTA.schema'
export { heroType } from './herotype.schema'
export { CallToAction } from './callToAction.schema'
export { LogoGallery } from './LogoGalleryType.schema'
export { accordionType } from './accordionType.schema'
